import fs from 'node:fs/promises';
const catalog=JSON.parse(await fs.readFile('data/keisei-main-stations.json','utf8'));
const BASE='https://keisei.ekitan.com/naritaacs-i/timetable/station';
const clean=s=>(s||'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const services={'Local':'local','Rapid':'rapid','Commuter Express':'commuterExpress','Rapid Ltd Express':'rapidLimitedExpress','Limited Express':'limitedExpress','Access Express':'accessExpress','Sky Liner':'skyliner','Morning Liner':'morningLiner','Evening Liner':'eveningLiner'};
const labels={local:'普通',rapid:'快速',commuterExpress:'通勤特急',rapidLimitedExpress:'快速特急',limitedExpress:'特急',accessExpress:'アクセス特急',skyliner:'スカイライナー',morningLiner:'モーニングライナー',eveningLiner:'イブニングライナー',other:'電車'};
function direction(h){const s=h.toLowerCase();return(s.includes('for keisei ueno')||s.includes('for oshiage')||s.includes('nishi magome')||s.includes('keikyu line'))?'up':'down';}
function dayBlock(html,key){const start=html.indexOf(`<nav v-show="is${key}">`);if(start<0)return'';const end=key==='Weekday'?html.indexOf('<nav v-show="isWeekend">',start):html.indexOf('<div v-show="isImage">',start);return html.slice(start,end>start?end:html.length);}
function parseEntries(block,dir){const out=[];for(const m of block.matchAll(/<li[^>]*class="[^"]*ekltip[^"]*"[^>]*>([\s\S]*?)<\/li>/g)){const b=m[1];const time=b.match(/ekldeptime[^>]*>\s*([0-2]?\d:\d{2})/i)?.[1];const type=clean(b.match(/ekltraintype[^>]*>([\s\S]*?)<\/span>/i)?.[1]).replace(/\bReserve\b/gi,'').trim();const destination=clean(b.match(/ekldest[^>]*>([\s\S]*?)<\/span>/i)?.[1]);if(time&&destination)out.push({time,dir,service:services[type]||'other',destination,origin:/eklfirst_train/.test(b)});}return out;}
async function page(index,d){const url=`${BASE}/254-${index}/${d}?dw=0`;const r=await fetch(url,{headers:{'user-agent':'train-watch-data-sync/1.0'}});if(!r.ok)return null;const html=await r.text();const h3=clean(html.match(/<h3[^>]*>([\s\S]*?)<\/h3>/i)?.[1]);if(!h3.includes('Keisei-Main line'))return null;const rev=html.match(/Revised\s+(\d{4})\/(\d{2})\/(\d{2})/i);const dir=direction(h3);return{dir,revision:rev?`${rev[1]}-${rev[2]}-${rev[3]}`:null,weekday:parseEntries(dayBlock(html,'Weekday'),dir),holiday:parseEntries(dayBlock(html,'Weekend'),dir)};}
const timetable={weekday:{},holiday:{}};let revision='2025-12-13';
for(let n=0;n<catalog.stations.length;n+=4){const batch=catalog.stations.slice(n,n+4);const results=await Promise.all(batch.flatMap(s=>['d1','d2'].map(d=>page(s[3],d).then(p=>({id:s[0],p})))));for(const {id,p} of results){if(!p)continue;revision=p.revision||revision;for(const day of ['weekday','holiday']){timetable[day][id]??=[];timetable[day][id].push(...p[day]);}}}
for(const day of ['weekday','holiday'])for(const id of Object.keys(timetable[day])){const seen=new Set();timetable[day][id]=timetable[day][id].sort((a,b)=>a.time.localeCompare(b.time)).filter(x=>{const k=`${x.time}|${x.dir}|${x.service}|${x.destination}`;if(seen.has(k))return false;seen.add(k);return true;});}
const now=new Date();const out={schemaVersion:1,railId:'keisei',operatorName:'京成電鉄',lineId:'main',lineName:'京成本線',dataMode:'station-timetable',dataVersion:`${now.toISOString().slice(0,10)}.1`,checkedAt:now.toISOString(),timetableRevision:revision,validThrough:null,source:{label:'京成電鉄 公式駅時刻表',url:'https://keisei.ekitan.com/naritaacs-i/timetable'},coverage:{stationTimetable:true,pass:false,realtime:false,terminalArrivals:false},services:labels,directions:{up:'上野・押上方面',down:'成田・空港方面'},stations:catalog.stations.map(([id,name,en],i)=>({id,name,en,i,line:'main'})),timetable};
await fs.mkdir('generated',{recursive:true});await fs.writeFile('generated/keisei-main.json',JSON.stringify(out,null,2)+'\n');
console.log(JSON.stringify({stations:out.stations.length,revision,weekday:Object.values(timetable.weekday).reduce((a,x)=>a+x.length,0),holiday:Object.values(timetable.holiday).reduce((a,x)=>a+x.length,0)},null,2));
